### ISSUE TITLE
Rework home page

### ISSUE THREAD

**Issue by vs0usa** [taiyomoe/taiyo#874]
- [x] Make the banner full-width (#876)
- [x] Add chapter pagination (#946)
- [x] Rework navbar (transparent at the top and make it dark as the users scrolls) (#923)
- [x] Texts too light, I want them bolder (#875)
- [x] Add a grid pattern background on the top-right corner (#876)
  - Reference: https://magicui.design/docs/components/grid-pattern
- [x] Add scrollshadow to the horizontal scrolling at the bottom (#875)
- [x] Use cache (#927)
